name: Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make all
            mkdir out/
            find . -type f -iname "*.pdf" -exec mv {} out/ \;

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Latest PDFs"
          automatic_release_tag: "latest"
          prerelease: false
          files: out/*
